// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CertsColumns holds the columns for the "certs" table.
	CertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tag", Type: field.TypeString, Size: 500},
	}
	// CertsTable holds the schema information for the "certs" table.
	CertsTable = &schema.Table{
		Name:       "certs",
		Columns:    CertsColumns,
		PrimaryKey: []*schema.Column{CertsColumns[0]},
	}
	// DdnSsColumns holds the columns for the "ddn_ss" table.
	DdnSsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "v4method", Type: field.TypeInt, Nullable: true},
		{Name: "v6method", Type: field.TypeInt, Nullable: true},
		{Name: "ipv6", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "rev6", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "ipv4", Type: field.TypeString, Nullable: true, Size: 16},
		{Name: "rev4", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "v4script", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "v4interface", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "v6script", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "v6interface", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "domains", Type: field.TypeJSON},
		{Name: "config", Type: field.TypeJSON},
		{Name: "result", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "status", Type: field.TypeBool},
		{Name: "webhook", Type: field.TypeJSON, Nullable: true},
	}
	// DdnSsTable holds the schema information for the "ddn_ss" table.
	DdnSsTable = &schema.Table{
		Name:       "ddn_ss",
		Columns:    DdnSsColumns,
		PrimaryKey: []*schema.Column{DdnSsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CertsTable,
		DdnSsTable,
	}
)

func init() {
}
